In [21]:
import pandas as pd

In [ ]:
df = pd.read_csv('winemag-data-130k-v2.csv', index_col=0)
df

In [30]:
df.columns = df.columns.str.lower().str.strip()
df

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [ ]:
df = df.dropna(subset = ['price', 'points'])
df

In [ ]:
data_final = df[(df['country'] == 'Portugal') & (df['points'] > 90)].copy()
data_final

In [34]:
data_final['custo_por_ponto'] = data_final['price'] / data_final['points'] 
data_final

C:\Users\Gabriel Felipe\AppData\Local\Temp\ipykernel_9824\2856748102.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_final['custo_por_ponto'] = data_final['price'] / data_final['points']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,custo_por_ponto
151,Portugal,"This bottling shows a rich, wood-aged wine, fu...",Gerações Colheita Seleccionada Branco,91,30.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Herdade Grande 2014 Gerações Colheita Seleccio...,Portuguese White,Herdade Grande,0.329670
157,Portugal,"From an estate in the south of the Alentejo, t...",Grande Reserva Tinto,91,26.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Casa Santa Vitória 2013 Grande Reserva Tinto R...,Portuguese Red,Casa Santa Vitória,0.285714
473,Portugal,"A powerful wine, richly structured and full of...",Gerações Colheita Seleccionada,92,34.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Herdade Grande 2010 Gerações Colheita Seleccio...,Portuguese Red,Herdade Grande,0.369565
642,Portugal,This is a new wine from the hands of master wi...,Monte de Carrapatelo Colheita Seleccionada Tinto,92,30.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Luis Duarte 2013 Monte de Carrapatelo Colheita...,Portuguese Red,Luis Duarte,0.326087
646,Portugal,As its name suggests this is a selection of ba...,Lagoalva Barrel Selection Tinto,92,23.0,Tejo,NaN,NaN,Roger Voss,@vossroger,Quinta da Lagoalva de Cima 2013 Lagoalva Barre...,Portuguese Red,Quinta da Lagoalva de Cima,0.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129130,Portugal,Bual is the grape that creates the medium-swee...,Colheita,93,NaN,Madeira,NaN,NaN,Roger Voss,@vossroger,Cossart Gordon 1995 Colheita Bual (Madeira),Bual,Cossart Gordon,NaN
129671,Portugal,"Two classic Dão grapes, Touriga Nacional and T...",Dona Georgina,93,60.0,Dão,NaN,NaN,Roger Voss,@vossroger,Quinta de Lemos 2010 Dona Georgina Red (Dão),Portuguese Red,Quinta de Lemos,0.645161
129680,Portugal,Old vines in a field blend give a rich structu...,Monte Cascas Grande Reserva,93,39.0,Douro,NaN,NaN,Roger Voss,@vossroger,Casca Wines 2011 Monte Cascas Grande Reserva R...,Portuguese Red,Casca Wines,0.419355
129685,Portugal,The red-juice grape Alicante Bouschet gives a ...,Comporta,93,50.0,Península de Setúbal,NaN,NaN,Roger Voss,@vossroger,Herdade da Comporta 2010 Comporta Alicante Bou...,Alicante Bouschet,Herdade da Comporta,0.537634
129901,Portugal,Wood fermentation and aging have given this fi...,NaN,91,30.0,Beira Atlantico,NaN,NaN,Roger Voss,@vossroger,Quinta de Foz de Arouce 2015 Cerceal (Beira At...,Cerceal,Quinta de Foz de Arouce,0.329670